### ISSUE TITLE
cannot find ImageMagicK 

### ISSUE THREAD

**Issue by adesolaadegboye** [CollectionFS/Meteor-CollectionFS#232]
Does anyone know why I am getting below error? I already have imageMagick installed on my Mac, $DYLD_LIBRARY_PATH setup, $MAGIC_HOME setup too and I am able to run imagemagick convert and identify command

=> Started MongoDB.  
I20140329-00:10:42.668(0)? TempStore: /tmp/cfs
I20140329-00:10:43.081(0)? GridFS init imagesGridStore on mongodb://127.0.0.1:3001/meteor
=> Started your app.

=> App running at: http://localhost:3000/
W20140329-00:10:43.185(0)? (STDERR) cfs-graphicsmagic could not find "graphicsMagic" or "imageMagic" on the system
W20140329-00:10:43.185(0)? (STDERR) 
W20140329-00:10:43.186(0)? (STDERR) packages/cfs-graphicsmagick.js:49
W20140329-00:10:43.186(0)? (STDERR)           throw new Error('cfs-graphicsmagic need binaries');  
W20140329-00:10:43.186(0)? (STDERR)                 ^
W20140329-00:10:43.187(0)? (STDERR) Error: cfs-graphicsmagic need binaries
W20140329-00:10:43.188(0)? (STDERR)     at packages/cfs-graphicsmagick/fsFile-gm.js:35
W20140329-00:10:43.188(0)? (STDERR)     at ChildProcess.exithandler (child_process.js:641:7)
W20140329-00:10:43.188(0)? (STDERR)     at ChildProcess.EventEmitter.emit (events.js:98:17)
W20140329-00:10:43.189(0)? (STDERR)     at maybeClose (child_process.js:743:16)
W20140329-00:10:43.189(0)? (STDERR)     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
=> Exited with code: 8

**Comment by Kunal1985** [comment]
Solution for Windows - 
Do not Install GraphicsMagic/ImageMagic to windows default location as it contains spaces within the folder structure like C:\Program Files (x86)\GraphicsMagick-1.3.21-Q8
Install GraphicsMagic/ImageMagic to a folder which does not have spaces
Example: D:\Installed\GraphicsMagick-1.3.21-Q8
The base installation takes care of updating the windows path variable, so no need to worry.
This worked for me.

**Comment by CA99** [comment]
There is a bug where gm/im has to be installed on the same drive letter as the Meteor application that's running. Here, you can see that the meteor application is running on E:\, but I have gm at D:\GraphicsMagick-1.3.21-Q8. When I move gm to E:\GraphicsMagick-1.3.21-Q8 and set the path accordingly, these errors go away.

![image](https://cloud.githubusercontent.com/assets/1342915/10433691/ea765510-70e1-11e5-9ebe-bd5efcdd2742.png)

I'm honestly not sure if this problem is in CFS or in Meteor itself.
