### ISSUE TITLE
Incomplete chunked encoding

### ISSUE THREAD

**Issue by nooitaf** [CollectionFS/Meteor-CollectionFS#312]
I have a page with lots of images (~40), each around 200kb but randomly some of them  (~4) throw an error. They are never the same. They start loading (i see them build up) but then they stop and this error is thrown. 

```
net::ERR_INCOMPLETE_CHUNKED_ENCODING
domrange.js:23 
```

domrange.js sits in the UI package, but i dont know how i could have done wrong in that regard.

I'm running Meteor Release `0.8.1.2` 

Anyone familiar with this? Could it be a memory issue on the server? It's using 400 of 490 MB. I'll might ramp it up tomorrow to 1GB just for testing but i fear its unrelated.

**Comment by adamgins** [comment]
@nooitaf @maomorales wondering if you resolved this... I am getting a similar issue outlines here https://github.com/CollectionFS/Meteor-CollectionFS/issues/690 I am struggling to resolve it. 

My error is random... ie I can upload the same image a few times and sometimes it works for all the transforms, sometimes it does not

**Comment by maomorales** [comment]
@adamgins - I'll solved the problem, however it does not mind I found the root cause of the problem.

First there was a content-length header missing, we fixed that in the source code of collectionFS a time ago. It fixed some problems, however the ERR_CONTENT_LENGTH_MISMATCH continued showing in some weird and random scenarios.

Check this out:
http://stkchf.bootstrup.com/cfs/files/chefphotos/t6TLmcs6NyicPu8ov/IMG-20140822-WA0001.jpg?store=chefphotos_horizontal

And now check this out:
http://kechef.com/cfs/files/chefphotos/t6TLmcs6NyicPu8ov/IMG-20140822-WA0001.jpg?store=chefphotos_horizontal

With the second one, you'll probably get the ERR_CONTENT_LENGTH_MISMATCH. The difference is that the second file is being served directly by nodeJS/meteor app to Chrome - where somehow there is some incompatible header with chrome.

The first URL is served by a cache server that we created, in order to avoid hits to NodeJS app server to download files (avoid as much as possible, as you know Node does not perform that well for this task) – it's a simple layer with a Varnish service. You can accomplish the same goal by using CloudFront. In the end it does hit NodeJS in order to cache the file for the first time or when cache is invalidated - but it serves the file with some different headers that work well on Chrome.

I'm sorry I cannot point you to the specific cause. I solved this with the cache by coincidence (as we wanted to cache anyways) and haven't had time to inspect in depth.

**Comment by adamgins** [comment]
@maomorales thanks. ok I just tried to divert using Cloudflare (the freeversion) and I ended up with a similar error:

```
Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
```

On the nginx side .. still seems to be cutting off the connection:

Jun 12 10:13:35 BuzzyDockerTestEnv1-buzzytest1 nginx-proxy:  nginx.1    | 2015/06/12 00:13:35 [error] 27#0: *2481 upstream prematurely closed connection while reading upstream, client: 108.162.249.224, server: test.buzzy.buzz, request: "GET /files/files/images/rGM4Gd6zrHrMAvLW9/thumb_IMG_3448.jpg?token=eyJhdXRoVG9rZW4iOiJwaGNhSzVUWnpwT3l1YlV3dTM1UERSeFQ2aU9EUm5DWTN4a1ppR0txZFN3In0%3D&store=thumbs HTTP/1.1", upstream: "http://172.17.0.187:80/files/files/images/rGM4Gd6zrHrMAvLW9/thumb_IMG_3448.jpg?token=eyJhdXRoVG9rZW4iOiJwaGNhSzVUWnpwT3l1YlV3dTM1UERSeFQ2aU9EUm5DWTN4a1ppR0txZFN3In0%3D&store=thumbs", host: "test.buzzy.buzz" 

With cloudflare, the file seems to stay there for a lot longer before the broken image symbol appears.

Did you have to upgrad to Cloudfare "pro" to get this to work?

Just wondering if GraphicsMagick is causing the issue and writing an invalid header?

**Comment by mlecoq** [comment]
@adamgins I have the same issue. Have you find a way to fix it ?

**Comment by adamgins** [comment]
sorry I moved away from CollectionFS
Adam Ginsburg
adam.ginsburg@buzzy.buzz
tel: +61 411 151 732
www.buzzy.buzz

**Comment by mlecoq** [comment]
The following lines

     if (fsFile.original.size < (2097152) * 10) {
        const chunkSize = fsFile.original.size / 10;
        FS.config.uploadChunkSize = chunkSize;
      }

fixed my issue

Except on chrome (where my photo is half grey)
