### ISSUE TITLE
fileObj Size Not Set

### ISSUE THREAD

**Issue by jralley** [CollectionFS/Meteor-CollectionFS#314]
I'm trying to upload an image from a url and I'm receiving the following error:

Exception in delivering result of invoking '/cfs.Images.filerecord/insert': Error: TransferQueue upload failed: fileObj size not set

Ideas?

**Comment by rbonslat** [comment]
I see that this is an old issue.  @aldeed, you mentioned that you intended for this to work on the client.  I switched to the server to get rid of the "fileObj size not set" error.  I now noticed that the transaction on the server seems to take much longer then on the client.  Was this issue fixed so that we can do it on the client side without getting the error message?
