### ISSUE TITLE
{{url}} and Filenames containing spaces

### ISSUE THREAD

**Issue by nooitaf** [CollectionFS/Meteor-CollectionFS#334]
The output of `{{url}}` should maybe unescape spaces? 
I didn't realize it in normal `<img>` elements, as the browser seems to add them automagicly, but if you do `<div style="background-image:url({{url}});">` the the image stays blank.

**Comment by RobertLowe** [comment]
@aldeed This issue should be reopen.

I ran into an issue where spaces in un-quoted `url()`s failed to load in Chrome Version 40.0.2214.111 (64-bit) on osx.

URLs should be properly escaped (spaces, etc). Also in my opinion the `.url` method should provide fully qualified paths.

A temporary work around for this issue is setting `.url(store: 'thing', filename: 'file')` so the filename is always a sane format.
