### ISSUE TITLE
503 (Service Unavailable) 

### ISSUE THREAD

**Issue by ghost** [CollectionFS/Meteor-CollectionFS#363]
after latest commit of cfs-collection (v0.4.10) I'm getting errors on modulus (deployed project):
(in development machine everything is ok)
  Error: "Queue" failed [503] Error in method "/cfs/files/:value/:value/", Error: Error:       EACCES, permission denied '/mnt/data/cfs'     at Object.fs.mkdirSync (fs.js:642:18)     at sync (/mnt... [undefined], Error

**Comment by jsvahn** [comment]
If you run in to this error today - add the cfs:gridfs package if you do not have it in your app. This makes cfs tempstore use gridfs instead of filesystem, thus avoids the attempts to access '/mnt/data/cfs'

**Comment by arvi** [comment]
I had to deal with this today upon deployment via mup deploy, I'm getting the same error. Adding cfs:gridfs results to "Meteor._wrapAsync has been renamed to Meteor.wrapAsync undefined" and upon checking it in atmosphere, it is not yet ready for production.

What I did to solve this issue is to login to our server then:
1. Go to app directory, in our case /opt/projectname/ 
2. Create these three directories: cfs/files/_tempstore
3. Go back to /opt/projectname then ls -la
4. Make sure cfs/files/_tempstore has same user and group permissions as "projectname"
5. Make sure the uploads directory has same user and group permissions as "projectname"
```
sudo chown -R meteoruser:root cfs
sudo chown -R meteoruser:root uploads
```

P.S I've defined our uploads directory in lib folder e.g
```
var baseUrl = "";

if (Meteor.isServer) {
    baseUrl = process.env.PWD;
}

Uploads = new FS.Collection('uploads', {
            stores: [new FS.Store.FileSystem('uploads', {
                path: baseUrl + '/uploads'})]
          });
```

Hope this helps! :)

**Comment by evolross** [comment]
I just ran into this very problem using `cfs:s3` and `mup` when deploying to production on AWS.  It still needs to write files to `cfs/files/_tempstore` in `/opt/projectname`. @arvi Your comment did the trick (but no need to do the `uploads` part because I'm using S3).  Thanks so much!

**Comment by bensventures** [comment]
I had the same problem and @arvi's comment did the trick. Thanks a lot.

**Comment by arvi** [comment]
@evolross @bensventures Nice! I'm glad I was able to help. :)

**Comment by minafarid** [comment]
@arvi I want to give you a cookie! AWESOME!

**Comment by cunneen** [comment]
Thank you @arvi !
