### ISSUE TITLE
uploadProgress and isUploaded are not reactive

### ISSUE THREAD

**Issue by Gaelan** [CollectionFS/Meteor-CollectionFS#397]
Is there a way to get them to update reactively that I don't know about?

**Comment by neopostmodern** [comment]
I ran into this just now and it seems like the `README` doesn't cover this yet, am I right?

Just to confirm if I got it right, is the following snippet the way it's supposed to be done?

```coffee
Tracker.autorun ->
  reactiveFileObj = MyFileCollection.findOne fileObj._id
  console.log "upload progress", reactiveFileObj.uploadProgress()
  console.log "is uploaded", reactiveFileObj.isUploaded()
  console.log "uploaded at", reactiveFileObj.uploadedAt
```

This does not really look like a reactive function to me - it seems the reactivity is caused by the `findOne` noticing a database change?
