### ISSUE TITLE
cfs_gridfs._tempstore.chunks not removed after file is saved

### ISSUE THREAD

**Issue by bitomule** [CollectionFS/Meteor-CollectionFS#415]
I've checked my db and I see a collection called cfs_gridfs._tempstore.chunks that takes up to  20mb in just one day. 

Is that an error or it's an expected behaviour. How do I clear that? 

I'm using the S3 adapter, I want to store my files there, not on db.

**Comment by zda** [comment]
Important note – I don't think clearing tempstore is a safe operation necessarily, at least not with the S3 adapter.

I say that because I have had an issue wherein my data was never making it to S3, and seems to have been hanging out in tempstore indefinitely. I recently upgraded from Compose sandbox to paid, and it seems to no longer be occurring, but if I see it again I'll post an issue with more details.
