### ISSUE TITLE
Change tempstore path

### ISSUE THREAD

**Issue by fpoirier1** [CollectionFS/Meteor-CollectionFS#445]
Hi,

My app is hosted on Modulus and as it has been mentionned before ModuIus doesn't allow access to full file system and it is recommended to GridFS instead. But, Modulus does provide paths for temporary storage and cloud storage. Is it possible to change the tempstore path to make it work with Modulus just like the `store : "/app-storage"` option ?

Thanks

**Comment by aramk** [comment]
Just an update - I think it might be worth the effort to try using GridFS or S3 instead of the `/app-storage` on Modulus. I ran an erroneous script which somehow removed some user data (though replaceable) and Modulus mentioned in an email that it doesn't keep backups for this cloud storage despite it being on S3. So treat it as temporary file storage I think.

**Comment by jsvahn** [comment]
for me this was solved by adding the cfs:gridfs package to the app. I used S3 for storage so I did not have it in the app before. This makes cfs tempstore use gridfs instead of filesystem, thus avoids the attempts to access '/mnt/data/cfs'

**Comment by CaptainN** [comment]
Using gridfs solved an error on Modulus that I think was caused by setting more than one servo (where I presume one servo thought a file was there that wasn't, and that would crash the entire app at startup, because it was in the queue...).

It solved it for months, until it inexplicably stopped working - again at startup, from something in a queue.

Now I have to apparently clone locally to maybe get it to work again (but presumably, without more than one servo, so I don't get the same missing lock file error again). This entire thing is very very fragile.
