### ISSUE TITLE
Prevent downloading files to not logged in users with CollectionFS

### ISSUE THREAD

**Issue by eMarek** [CollectionFS/Meteor-CollectionFS#449]
As is said here https://github.com/CollectionFS/Meteor-CollectionFS#security, there is "download", a custom type of allow/deny function. I am trying to prevent not logged in users to download uploaded files like this:

```
Avatars.allow({
    download: function(userId, file) {
        if(userId) {
            return true;
        } else {
            return false;
        }
    }
});
```

The problem is that it doesn't work. What am I doing wrong?

**Comment by jchristman** [comment]
I'm having the same issue as eMarek had in that the userId passed to the download authenticator is always false. It seems that no matter what I do, the authToken is not being generated for the URL.

I've looked at https://github.com/CollectionFS/Meteor-cfs-access-point/blob/master/access-point-common.js to see if I could find the issue, but I am unable to find any problems. When I do a ```console.log(Accounts._storedLoginToken())``` to see if that's broken, it returns a valid login token. I also did a ```console.log(Meteor.isClient && typeof Accounts !== "undefined" && typeof Accounts._storedLoginToken === "function")``` to see if that "if statement" was failing, but it returned true, which implies to me that the code to generate the authToken is being reached in the code.

My relevant code for generating the URL is here:
```
// Code is here: https://github.com/jchristman/meteor-os/blob/master/builtins/file-browser/context-menus/fb-file-context-menu.js

var fsFile = MeteorOS_FS.findOne(fileID);
var url = fsFile.url({download : true, auth : true}); // I tried this with and without the auth param, as well as a number
console.log(url);
```

My  download function is here:
```
// Code is here: https://github.com/jchristman/meteor-os/blob/master/config/fs-config.js

download: function(userId, file) {
    console.log(userId, file.owner);
    return true;
}
```

To reproduce the issue, follow these steps to run the server:
```
git clone https://github.com/jchristman/meteor-os.git
cd meteor-os/example
meteor
```

Then, perform these steps in the application:
1. Register a user (I usually use the user "a" and password "asdf")
2. Upload a file in the "File Browser" window. You can drag and drop the file or click the "Upload" button.
3. Right-click on the uploaded file and select the "Download File" option. At this point, the server will ```console.log(userId, file.owner)``` and the client will ```console.log(url)```. The userId is always false because the url has no authToken
