### ISSUE TITLE
Need help with downloading files from cfs:gridfs

### ISSUE THREAD

**Issue by willemx** [CollectionFS/Meteor-CollectionFS#509]
I am using cfs:gridfs to store mediafiles for my project and using cfs:ui helpers for display/playback of media. This is all working fine.
Now I need to get some mediafiles back to my client as "real files", so I want to download them from within my app and store them on the client local filesystem.
Could someone provide me with a little example how to do this?
I can't use the url helper with the download option, because I want to control how the file is stored (location, filename, conversions,...).
After some googling I came across a method "retrieveBlob" which looks exactly like what I need but I can't find it anywhere in the cfs docs. Has this been deprecated? ...or is there some other method to get files to the client?

**Comment by nooitaf** [comment]
I don't think its possible to control the location of the file on the client. That might even be a major security issue. You can use `transformRead` to change the file before downloading tho.

Maybe [GroundDB](https://github.com/GroundMeteor/db) might help you with localstorage (in the browser).

**Comment by willemx** [comment]
So, if I drop the location change requirement (maybe just a subdir?), is there a way that I could do something like:

    mediacollection.retrieveBlob(this._id, function(fileItem) {
      if (fileItem.blob)
        saveAs(fileItem.blob, fileItem.filename)
      else
        saveAs(fileItem.file, fileItem.filename);

as in this example:
 https://github.com/CollectionFS/Meteor-cfs-example-filemanager

...if only I could find this method "retrieveBlob"...

**Comment by nooitaf** [comment]
Even a subdirectory is still somewhere in your userspace. And thats not how browsers are supposed to handle files. Just imagine a browser writing files anywhere on your system without asking. There might even be important stuff in your downloads folder you dont want to lose because some website decides to write some files to it. So it always increments filenames and has no access to your files without explicit permission of the user.

iirc, a blob is a Browser/Client concept. Its a way for the browser to move stuff around internally. You would have to write it to a blob first, before reading from it (like a audio recording). The server can't write to a blob.
https://developer.mozilla.org/en-US/docs/Web/API/Blob

**Comment by aldeed** [comment]
@willemx, there is no built-in way to get a blob anymore, but you could potentially read the file data into one using a normal xmlhttprequest to the file's URL. However, I don't recommend doing that if the files are large because all binary data will be cached in memory. It will slow down and may crash the browser. Also, you'll then have to resort to using [FileSaver](https://github.com/eligrey/FileSaver.js/) to save the blob, but as @nooitaf says, you still won't have any control over where and how it's saved. Depending on the browser and the user's preferences for that browser, they either see a Save As dialog or the file goes directly into their Downloads folder.

I agree that doing transformations on the server and using the normal download URL to download is best. This is why new CFS does not have retrieveBlob anymore.

**Comment by willemx** [comment]
Found a way to do my file manipulations serverside and can now use the standard download procedure using the url-helper. Everything works as expected now.
Thanks everyone!
