### ISSUE TITLE
{{this.url}}, doesn't work on IE<10

### ISSUE THREAD

**Issue by Ethaan** [CollectionFS/Meteor-CollectionFS#515]
So we have "dynamic routes" using

 Iron router
But it seems like, the dynamic routes with images dosnt work

if you have a chance check [this web](http://padonde.mx)

It this a Iron router problem? or FSCollection url problem?

Actually the problem just appear when {{this.url}} have an image on it, if {{this.url}} is empty the route work.

Thanks in advice

**Comment by jeanfredrik** [comment]
I have the same issue in IE9 with `{{this.url}}` on images. I get the following log message in the debugger:

```
LOG: Exception from Tracker recompute function:FS.Utility.btoa: Cannot base64 encode on your system
```

I also have Iron Router installed.

**Comment by raix** [comment]
We might need to add a polyfill for base64 encoding (cant remember if its accessible from the meteor ejson package)

**Comment by todda00** [comment]
Confirmed I am also having this issue with IE9, page will not load when this.url is present at all.

**Comment by todda00** [comment]
Found this SO about btoa and atob with IE: http://stackoverflow.com/questions/11524268/atob-not-working-in-ie

So could something like this be used if the btoa function is not natively used here: https://github.com/CollectionFS/Meteor-CollectionFS/blob/9e45f0b2be9b10f1e3d96b34c35979d93a59ffea/packages/base-package/base-common.js#L274

and here: https://github.com/CollectionFS/Meteor-CollectionFS/blob/9e45f0b2be9b10f1e3d96b34c35979d93a59ffea/packages/base-package/base-common.js#L290

I am not sure where you would want to keep a polyfill like this in the code to keep it all clean, but would be willing to create a PR to at least get IE9 to be able to view / download files. I don't need to require adding files for IE9, I can force users to have a better browser for that at least.

**Comment by aldeed** [comment]
@todda00 base-package is a good place for the polyfill, in a separate, new file.

**Comment by todda00** [comment]
ok, so I sat down to start to work on this, and I am having trouble getting CFS going in a local package. I have done this with other Meteor packages before, but it seems that CFS does things differently and I can't get it to read cfs:base-package from my local packages directory. This is what I did:

Forked Meteor-CollectionFS to my personal github
git clone https://github.com/todda00/Meteor-CollectionFS.git
mrt link-package to symlink the package directory into the application

meteor remove cfs:base-package
meteor add cfs:base-package
The symlink shows and I can edit files, but the package is not actually the one being used, its still using the published version.

The CONTRIBUTORS.GUIDE.md is blank, so that wasn't any help lol.

Any help would be appreciated, thanks.

**Comment by nooitaf** [comment]
A symlink to the packages folder should be sufficient?
````bash
cd meteorproject
ln -s /path/to/cfs-clone/packages packages
````

**Comment by todda00** [comment]
@nooitaf Thanks for the explanation, I was so close - I had Meteor-CollectionFS folder under packages, then packages, then the CFS packages, once I only symlinked the CFS packages folder to the app's packages dir, I was good to go. I'm going to apply this polyfill and see how it goes for IE.

**Comment by todda00** [comment]
Created a PR: https://github.com/CollectionFS/Meteor-CollectionFS/pull/671
