### ISSUE TITLE
Updated event - url

### ISSUE THREAD

**Issue by theduke** [CollectionFS/Meteor-CollectionFS#528]
In the following code, the url (fileObj.url()) is sometimes emtpy!
How come? Is there another event that I can use (on the client) that definitely has the url set?

```javascript
fileObj.on('uploaded', function(obj) {
          // File was uploaded, url is available, so display it now.
          console.log('uploaded', fileObj.url());
});
```

**Comment by aldeed** [comment]
It's because the "uploaded" event on the client is currently fired when the last chunk is sent, whereas technically it isn't truly uploaded (and `url` won't be set) until server sends confirmation of receiving that chunk. I can't find the issue number right now, but there is another issue about this so I'm closing this as a duplicate.

The best workaround at the moment is to set up a reactive dependency on the value of `fileObj.url()`.

**Comment by theduke** [comment]
Found the issue, if someone else needs it: #323
