### ISSUE TITLE
Security (server-side)

### ISSUE THREAD

**Issue by niallobrien** [CollectionFS/Meteor-CollectionFS#744]
Hi, I'm looking at using this package to handle file uploads, but I'm wondering why you `...recommend doing all inserts on the client (managing security through allow/deny)`?
I personally prefer to use Meteor methods and not fiddle with allow/deny security issues.
In a traditional web req/res setup, I’d transfer an image to the server to process & store anyways, how is this any different?

Thanks in advance.

**Comment by Zodiase** [comment]
Actually I think Meteor's way would also be insert on the client with allow/deny on server. See the [docs about security](http://docs.meteor.com/#/full/dataandsecurity).

**Comment by Zodiase** [comment]
By the way you can surely deny everything and handle the insert on the server as well.

**Comment by niallobrien** [comment]
There is no allow/deny on the server. It's Meteor methods and method stubs on the client simulate the response (latency compensation). Allow/deny rules are simply too unpredictable.

**Comment by Zodiase** [comment]
@niallobrien
allow/deny is defined on server and is handled on the server, it however only moderates the operations sent from the client.

**Comment by Zodiase** [comment]
@niallobrien 
Sure you could also define allow/deny on the client as stubs. But you need them defined on the server to really handle the security.

**Comment by niallobrien** [comment]
Ah cool. So can we come away from allow/deny syntax and just use Meteor methods?

**Comment by Zodiase** [comment]
In terms of uploading files, I don't suppose you would attach all the data of a small file, say 30 MB, to a method call? That is brutal.

I mean, really, learn the right way of using allow/deny, which is something generic in Meteor. It has nothing to do with CollectionFS. If you avoid using allow/deny and manage all collection operations on the server with calls, you are using Meteor wrong.

**Comment by niallobrien** [comment]
That 30mb file has to upload to the server anyways, I'm just trying to understand the difference here.

**Comment by Zodiase** [comment]
@niallobrien 
OK, I'll try to explain the two different type of processes so you could see the difference.

First let me start with a direct server method call, since it's shorter.
The whole file gets attached to the request and the request is sent to server, with an AJax call for example. It'll probably be a POST request given the size of the file. And the client would have to wait for the whole file to be sent to receive the response from the server. If somebody has a 32 KB/s upload bandwidth, that's 16 minutes of nothingness just the browser sending the file. And then the server code receives the request which is at least 30MB in size, hope it doesn't run out of memory and crash. The rest is easy to imagine.

Now what about using FsCollection.insert(File)?
First, the file gets wrapped into a FsFile type, which at this time would only contain meta data, so probably a few bytes. Then the client script passes it to the client side allow/deny policies for insert operations, if they are defined, to get permission. If the operation is allowed, the client script then calls the secret server method to request the insert operation, still only with that tiny FsFile argument. The secret server method **receives the request and checks against the allow/deny policies for insert operations defined in the server code**. If the operation is allowed, a FsFile record is added to the FsCollection on the server and it is marked as `isUploaded:false` and now the secret method responds the request with a green light and the client script would start the real uploading process, where it chunks the file into small pieces, say 1MB. Then it calls another secret server method and basically say "hey the *nth* chunk of the file I'm trying to upload is here". Of course this call would still need to first pass the allow/deny policies defined on the client side for *update* operations. When the server received the request, it will check against the allow/deny policies defined in the server code for *update* operations, process the update by storing the small chunk into a storage and then tell the client script that this is done. (This gives the client opportunities to resend chunks of data in the case of a connection failure, without failing the whole task.) The client keeps sending the chunks one by one until all chunks of the file is received and confirmed by the server, and then the client tries to update the file as `isUploaded:true`. Now that's the end of the insert operation at the client side and it calls the corresponding callback, if provided, to notify that the file is ready on the server.

**Comment by Zodiase** [comment]
@niallobrien 
Oh I forgot to add that, since the file is sent chunk by chunk, this allows the client script to report the upload progress.

**Comment by niallobrien** [comment]
Cool, thanks for that.
