### ISSUE TITLE
get warning when upload file

### ISSUE THREAD

**Issue by Silence-wzy** [CollectionFS/Meteor-CollectionFS#894]
The provided value 'undefined' is not a valid enum value of type XMLHttpRequestResponseType.

who have ever solved this issue?

**Comment by msio777** [comment]
I am interested too

**Comment by cskaandorp** [comment]
+1

**Comment by Sojourneer** [comment]
+1

**Comment by advany** [comment]
+1

**Comment by Cherviakov** [comment]
+1

**Comment by andrewash** [comment]
+1

**Comment by geeksville** [comment]
Alas, I haven't setup an environment to build cfs from source (a bit of a meteor noob).  But if it helps anyone else it seems like the error is:

https://github.com/CollectionFS/Meteor-CollectionFS/blob/master/packages/upload-http/upload-http-client.js#L25

Needs to pass in "responseType" as an option and it is not.

**Comment by dsalmen** [comment]
+1

**Comment by ilacyero** [comment]
+1 I have the same warning.

**Comment by rafaelcorreiapoli** [comment]
+1

**Comment by pedrorodrigues** [comment]
+1

**Comment by nooitaf** [comment]
@geeksville "building cfs package from source" with meteor is pretty easy. 

Just clone this repo...
`````bash
git clone https://github.com/CollectionFS/Meteor-CollectionFS
`````
You will now have an emtpy meteor project with all cfs packages ready to go.
Every `meteor add cfs:...`  you add in here will be loaded from `/packages`

As soon as you do `meteor add cfs:standard-packages` meteor will first check if there is a `/packages` folder in your project which contains a package with that name and a version number same or higher then the one on atmosphere. If it finds one it will use the local one.

After your app started, you can change the package in the `/packages` folder and it should rebuild as soon as you save.

You could also add the `/packages` folder or just the packages needed into your existing project, just make sure that you check the dependencies because those might refer to a different versions and if that version does not exist in your packages folder it might just get it from atmosphere.

**Comment by geeksville** [comment]
ok - thanks for the pointers.  I'll do this tomorrow and send in a PR for this.
